version: "3"
services:
  # udagram:
  #   container_name: backend
  #   image: udagram-api
  #   volumes:
  #     - $HOME/.aws:/root/.aws
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  reverseproxy:
    container_name: reverseproxy
    image: reverseproxy
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-feed:
    container_name: backend-feed
    image: udagram-api-feed
    volumes:
      - ./.aws:/root/.aws
    env_file:
      - .env
  backend-user:
    container_name: backend-user
    image: udagram-api-user
    env_file:
      - .env
  frontend:
    container_name: frontend
    image: udagram-frontend:local
    env_file:
      - .env
    ports:
      - "8100:80"
