version: "3"
services:
  reverseproxy:
    container_name: reverseproxy
    image: xuanbinh313/reverseproxy:v1
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-feed:
    container_name: backend-feed
    image: xuanbinh313/udagram-api-feed:v1
    volumes:
      - ./.aws:/root/.aws
    env_file:
      - .env
  backend-user:
    container_name: backend-user
    image: xuanbinh313/udagram-api-user:v1
    env_file:
      - .env
  frontend:
    container_name: frontend
    image: xuanbinh313/udagram-frontend:v1
    env_file:
      - .env
    ports:
      - "8100:80"
