version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17

    steps:
      - checkout

      # Install Docker inside the CircleCI container
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user xuanbinh313/udagram-api-user:v1

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed xuanbinh313/udagram-api-feed:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend xuanbinh313/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy xuanbinh313/udagram-reverseproxy:v1

      - run:
          name: Push Docker Image to DockerHub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push xuanbinh313/udagram-api-user:v1
            docker push xuanbinh313/udagram-api-feed:v1
            docker push xuanbinh313/udagram-frontend:v1
            docker push xuanbinh313/udagram-reverseproxy:v1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
