apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  namespace: default
  labels:
    app: reverseproxy
spec:
  selector:
    app: reverseproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080